### ISSUE TITLE
Tests are failing when parsing in non-strict mode

### ISSUE THREAD

**Issue by afri** [lezer-parser/javascript#1]
When I patch up lezer-generator/test/test-parse.ts to parse files with `{strict:false}`, then many of the javascript tests fail.
E.g. expression/Arrays yields:
```
  2) expression
       Arrays:
     Error: Expected ArrayExpression in ExpressionStatement, got AssignmentExpression at 0 
Script(ExpressionStatement(AssignmentExpression(ArrayPattern("[","]"),⚠),";"),ExpressionStatement(ArrayExpression("[",String,"]"),";"),ExpressionStatement(ArrayExpression("[",String,",","]"),";"),ExpressionStatement(ArrayExpression("[",String,",",VariableName,"]"),";"),ExpressionStatement(ArrayExpression("[",",",VariableName,"]"),";"),ExpressionStatement(ArrayExpression("[",AssignmentExpression(VariableName,Equals,Number),"]"),";"))
      at Iteration.enter (node_modules/lezer-generator/dist/test.js:123:23)
      at Iteration.doEnter (node_modules/lezer-tree/dist/tree.js:30:26)
      at TreeBuffer.iterChild (node_modules/lezer-tree/dist/tree.js:586:33)
      at TreeBuffer.iterChild (node_modules/lezer-tree/dist/tree.js:588:30)
      at TreeBuffer.iterInner (node_modules/lezer-tree/dist/tree.js:575:30)
      at Tree.iterInner (node_modules/lezer-tree/dist/tree.js:413:23)
      at Tree.iterInner (node_modules/lezer-tree/dist/tree.js:413:23)
      at Tree.iterate (node_modules/lezer-tree/dist/tree.js:399:14)
      at testTree (node_modules/lezer-generator/dist/test.js:108:10)
      at run (node_modules/lezer-generator/dist/test.js:152:17)
      at Context.it (test/test-javascript.js:13:22)
```

**Comment by marijnh** [comment]
Let's continue this discussion at https://github.com/lezer-parser/lezer/issues/12
